### ISSUE TITLE
Seeing if episode is watched or not

### ISSUE THREAD

**Issue by Schiznit** [pecinko/skin.amber#48]
Would be great to add something to make it clearly visible if a tv episode has been watched or not. Is with Quartz for instance.

**Comment by Schiznit** [comment]
No way to add this function? As I mentioned before, it works in Quartz for example.

**Comment by pecinko** [comment]
What function? Screenshot? Please use forums for support.

**Comment by Schiznit** [comment]
On Quartz there is a dot next to the file. When full, tv show is unwatched, when there is no dot, its watched. I use file list on tv shows as the tvdb scraper does not work.
