### ISSUE TITLE
Live TV does not work with Helix

### ISSUE THREAD

**Issue by jowi24** [pecinko/skin.amber#62]
After upgrading to KODI using today's master snapshot from skin.amber I am experiencing issues with Live TV. The main menu still shows the "old" entry "Live TV" instead of "Radio" and "TV". Selecting, e.g., "Live TV" -> "TV channels" results in a black screen. Everything is okay, when using the confluence skin.

**Comment by pecinko** [comment]
please use forum for support. I don't have a working PVR setup ATM.

**Comment by jowi24** [comment]
I do not need support. The amber skin is broken regarding PVR support, thats why i opened an issue. If you can't fix it yourself, the issue should remain open so others can recognize the issue and provide a fix.
