### ISSUE TITLE
seen position save doesn't work when item played from shelf

### ISSUE THREAD

**Issue by beam** [pecinko/skin.amber#69]
Playing started from home screen shelf doesn't save current position on stop.
Ver 2.0.10 on Win and ArchLinux

Any idea?

Kdyby nebylo jasny jak to myslim, tak to muzu napsat cesky :)

**Comment by beam** [comment]
Could somebody confirm this? Or is it just my local problem?

**Comment by jester-xbmc** [comment]
Confirmed,not an skin issue, kodi issue

http://trac.kodi.tv/ticket/15660

**Comment by beam** [comment]
Fixed in 14.1 test build.
