### ISSUE TITLE
Fails to install: (missing files)

### ISSUE THREAD

**Issue by arctelix** [pecinko/skin.amber#80]
Issue occurs when installing master from zip. Seems to be a wide spread issue.  All the relevant info i can find in the log is here (not very helpful):

ERROR: failed to load requested skin 'skin.amber'
13:28:30 T:13276 INFO: Unloading old skin ...
13:28:30 T:13276 DEBUG: ------ Window Deinit () ------
13:28:30 T:13276 DEBUG: ------ Window Deinit (AddonBrowser.xml) ------
13:28:30 T:13276 DEBUG: ------ Window Deinit (Pointer.xml) ------
13:28:30 T:13276 DEBUG: CTextureBundleXBT::Cleanup - Closed bundle
13:28:30 T:13276 INFO: load skin from: C:\Program Files (x86)\Kodi\addons\skin.confluence (version: 2.5.12)

After several attempts to install i just went into deactivated addons, activated it, and I was able to successfully change to amber.  

After activating skin:
13:34:59 T:13060 DEBUG: Addon skin.amber requires xbmc.gui version 5.0.1 which is not available

Could not find any occurrences of xbmc.gui version 5.0.1 in the code so not sure why that error is coming up.

Unfortunately, I am not familiar enough with kodi skinning to be of more help on this.

**Comment by arctelix** [comment]
jester-xbm's pull reqeust #78 seems to have solved this issue.

**Comment by jester-xbmc** [comment]
can be closed, #78 has been pulled
